# Generated by Django 5.2.8 on 2025-11-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmasterapp', '0002_searchhistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('ticket_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='searchHistory',
        ),
    ]
